name: lean's openwrt

on:
  push:
    branches:
      - lean
    paths:
      - '.github/workflows/main.yml'
      - 'patches/**'
      - 'config_rk3328'
  schedule:
    - cron: '09 08 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: lean

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          sudo docker image prune -a -f
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3.5 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          git config --global user.name "Chuck"
          git config --global user.email "fanck0605@qq.com"

      - name: Install Repo
        run: |
          rm -rf repo
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          rm -rf repo

      - name: Initialization Source
        run: |
          rm -rf friendlywrt-rk3328
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle
          repo sync -c --no-clone-bundle -j8

      - name: Install lean's openwrt
        run: |
          cd friendlywrt-rk3328
          rm -rf friendlywrt
          git clone https://github.com/coolsnowwolf/lede friendlywrt
          cd friendlywrt
          git apply ../../patches/002-openwrt-apply-friendlywrt.patch

      - name: Patch Kernel
        run: |
          cd friendlywrt-rk3328/kernel/
          wget -O net/netfilter/xt_FULLCONENAT.c https://raw.githubusercontent.com/Chion82/netfilter-full-cone-nat/master/xt_FULLCONENAT.c
          git apply ../../patches/001-kernel-add-full_cone_nat.patch
          git apply ../../patches/004-kernel-add-cifsd.patch

      - name: Customize Configuration Files
        run: |
          cp config_rk3328 friendlywrt-rk3328/configs/config_rk3328

      - name: Swap wan and lan
        run: |
          cd friendlywrt-rk3328/friendlywrt
          git apply ../../patches/003-openwrt-swap-wan-and-lan.patch

      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          ./build.sh nanopi_r2s.mk

      # clean compile files, release disk space
#      - name: Clean compile files
#        run: |
#          cd friendlywrt-rk3328
#          rm -rf `ls | grep -v "out"`

      - name: Fix FriendlyWrt rootfs owner and group
        run: |
          sudo losetup -o 100663296 /dev/loop99 friendlywrt-rk3328/out/*.img
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount /dev/loop99 /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d /dev/loop99

      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          gzip friendlywrt-rk3328/out/*.img
          cp friendlywrt-rk3328/out/*.img* ./artifact/

      - name: Save Configurations
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/diffconfig.sh > ../../artifact/config-lite
          cp .config ../../artifact/config-full

      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt
          path: ./artifact/
